apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: wjn1/ticketing-expiration
          resources:
            limits:
              memory: '512Mi'
              cpu: '500m'
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              # should NATS_CLUSTER_ID value be ticketing?
              # yes, the ticketing app, not the tickets service
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
